# Generated by Django 6.0.1 on 2026-01-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_maquinaria', models.CharField(help_text='Nombre o código de la maquinaria', max_length=100)),
                ('operador', models.CharField(help_text='Nombre del operador que realiza la inspección', max_length=100)),
                ('fecha', models.DateField(auto_now_add=True, help_text='Fecha automática de la revisión')),
                ('motor', models.BooleanField(default=False)),
                ('transmision', models.BooleanField(default=False)),
                ('frenos', models.BooleanField(default=False)),
                ('sistema_electrico', models.BooleanField(default=False)),
                ('bateria', models.BooleanField(default=False)),
                ('llantas', models.BooleanField(default=False)),
                ('fugas', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, help_text='Comentarios adicionales')),
            ],
        ),
    ]
